Pinning library versions and adding Python version to README
qurator-spk/sbb_binarization pull request #44
Opened 2022-08-22 08:48 UTC by apacha

This PR updates the requirements.txt (to pin specifically tested versions that actually work) as well as adding a tested Python version information to the README. Later versions will not work because of loading serialized h5 models causes marshalling errors.

Also adding `.idea` directory to list of ignored directories.

Fixes #39

2022-08-22 15:43 UTC, mikegerber commented
@kba Pinned versions might be undesirable with ocrd_all, am I right in this assumption?

2022-08-22 15:45 UTC, apacha commented
I can also remove the pin from ocrd

2022-08-22 16:00 UTC, cneud commented
ocrd also includes `numpy` via [ocrd_utils](https://github.com/OCR-D/core/blob/master/ocrd_utils/requirements.txt), but deliberately does not pin a version due to different requirements by different TF versions.

2022-09-21 10:09 UTC, kba requested changes
I appreciate the idea and this is how requirements.txt should actually be used but for compatibility reasons with other OCR-D software, I'd appreciate less restrictive pinning.

2022-09-21 10:09 UTC, kba commented on requirements.txt
> +opencv-python-headless==4.6.0.66
In OCR-D we use the `requirements.txt` in the same way as the `install_requires` mechanism in setup.py, i..e. we specify maximal version ranges for compatible libraries. For `opencv-python-headless` we deliberately do not restrict the version range to support the most environments possible. Unless there are very good reason why only this version should be supported, I'd prefer to not pin it.

2022-09-21 10:09 UTC, kba commented on requirements.txt
> +tensorflow==2.6.2
Same issue from ocrd_all's perspective. We do set minimum versions for tensorflow and in fact, tensorflow 2.6.2 is currently used (except for the tensorflow processors still on 1.15.x) but for the same reason as for opencv, we want to support the widest possible range of supported versions.
```suggestion
tensorflow>=2.4
```

2022-09-21 10:19 UTC, apacha commented on requirements.txt
> +tensorflow==2.6.2
I think supporting later versions of tensorflow is a good idea. We should just ensure that the binarization model that is provided for downloading is actually compatible to those versions (spoiler: the models downloaded from https://qurator-data.de/sbb_binarization/ are not - I had to open and re-save them in TF 2.6.2 for being able to use them in TF 2.9). That's why I proposed to pin TF to a version where the current model definitely works.

2022-09-21 10:21 UTC, apacha commented on requirements.txt
> +opencv-python-headless==4.6.0.66
For OpenCV I'm pretty certain that almost any version will work, as we just use it for reading and writing images, so I've removed the pin.

2022-09-21 10:59 UTC, kba commented on requirements.txt
> +tensorflow==2.6.2
But it should work with 2.4.0 upwards? eynollah does specify `>= 2.4.0` as well, calamari depends on `>= 2.5.0`, actually installed currently is `2.6.2`. Unless 2.4 does not work with the current models anymore, I would prefer to keep the minimum version. If we do need to upgrade the dependency, I would want to coordinate the change across projects.

> spoiler: the models downloaded from https://qurator-data.de/sbb_binarization/ are not - I had to open and re-save them in TF 2.6.2 for being able to use them in TF 2.9

@vahidrezanezhad @mikegerber Maybe it would make sense to provide the loaded-updated-and-saved models for later tensorflow versions via qurator-data.de? We have a (currently unused) `version_range` mechanism in the resource manager for this purpose and this would be a good use case to test it AFAICT.

2022-09-22 10:11 UTC, apacha commented on requirements.txt
> +tensorflow==2.6.2
I've made the converted models in the (more) portable TF format available here, if you are interested: https://github.com/apacha/sbb_binarization/releases/tag/pre-trained-models

2022-09-27 07:54 UTC, mikegerber commented
Side note: For the legacy sbb_textline_detection we had to fix OpenCV to a DIFFERENT version, see https://github.com/qurator-spk/sbb_textline_detection/issues/60

2023-04-14 11:39 UTC, cneud commented
@apacha Thank you again for your contributions! But since the pinning is problematic for OCR-D and the supported Python versions have now been documented in https://github.com/qurator-spk/sbb_binarization/commit/42bca1441cd9535c7af8b98d62eed550bfe3ddd6, I will close here.

2023-04-14 11:39 UTC, closed without merging