Improve tooling and add OCR-D CLI
qurator-spk/sbb_binarization pull request #5
Opened 2020-10-15 16:33 UTC by kba

* add `setup.py`, `requirements.txt`, `Makefile`
* clean up sbb_binarizer code and split CLI into own module
* proof-of-concept OCR-D CLI

TODO:

* [ ] Fix conversion from SbbBinarizer OpenCV2 image to PIL
* [ ] Refactor SbbBinarizer to load the model once and have a stateless `run` method
* [ ] Setup CI
* [ ] Improve documentation

2020-10-15 16:43 UTC, kba commented on sbb_binarize/ocrd_cli.py
> +    color_coverted = cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
I need help here: @vahidrezanezhad @bertsky @mikegerber any idea how to properly convert the cv2 image from the binarizer to PIL?

2020-10-15 17:27 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +    color_coverted = cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
I don't think you need any color conversion on the way back at all. The result should be a `np.uint8` type binary mask (with 255 as white and 0 as black). You can convert that to an `L` mode `PIL.Image` simply by `Image.fromarray`. Or you do `> 0` bools and convert to an `1` mode Image with `fromarray`.

2020-10-15 17:49 UTC, bertsky requested changes

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
It would be helpful to document the ramifications of this choice here (speed vs quality?)

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
Has line-level processing really been tested?

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "description": "models directory.",
Relative paths, too?

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                page_image, page_xywh, _ = self.workspace.image_from_page(page, page_id)
Should probably rule out binarized images on the input side:
```suggestion
                page_image, page_xywh, _ = self.workspace.image_from_page(page, page_id, feature_filter='binarized')
```

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                page.add_AlternativeImage(AlternativeImageType(filename=bin_image_path, comment="binarized"))
Should definitely append to (not replace) the image features (like cropped, normalized etc):
```suggestion
                page.add_AlternativeImage(AlternativeImageType(filename=bin_image_path, comment=page_xywh['features']+",binarized"))
```

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                regions = page.get_AllRegions(['Text', 'Table'])
Perhaps limit recursion here to only the top level?

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                    region_image, region_xywh = self.workspace.image_from_segment(region, page_image, page_xywh)
```suggestion
                    region_image, region_xywh = self.workspace.image_from_segment(region, page_image, page_xywh, feature_filter='binarized')
```
(see above)

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                            AlternativeImageType(filename=region_image_bin_path, comments='binarized'))
```suggestion
                            AlternativeImageType(filename=region_image_bin_path, comments=region_xywh['features']+',binarized'))
```
(see above)

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                regions = page.get_AllRegions(['Text', 'Table'])
(If you do, you must also use a _different_ iterator for the line level: fully recursive `['Text']` regions.)

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                            line_image, line_xywh = self.workspace.image_from_segment(line, page_image, page_xywh)
```suggestion
                            line_image, line_xywh = self.workspace.image_from_segment(line, page_image, page_xywh, feature_filter='binarized')
```
(see above)

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                            line_image, line_xywh = self.workspace.image_from_segment(line, page_image, page_xywh)
No, wait, this should actually use the region images for reference (because they might have been deskewed independently):
```suggestion
                            line_image, line_xywh = self.workspace.image_from_segment(line, region_image, region_xywh, feature_filter='binarized')
```

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                                AlternativeImageType(filename=line_image_bin_path, comments='binarized'))
```suggestion
                                AlternativeImageType(filename=line_image_bin_path, comments=line_xywh['features']+',binarized'))
```
(see above)

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                        page_id=page_id,
No, `page_id` (as defined above) is only for logging, here only true pageId is allowed:
```suggestion
                        page_id=input_file.pageId,
```

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                                page_id=page_id,
```suggestion
                                page_id=input_file.pageId,
```
(see above)

2020-10-15 17:49 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                                    page_id=page_id,
```suggestion
                                    page_id=input_file.pageId,
```
(see above)

2020-10-15 17:49 UTC, bertsky commented on setup.py
> +    description='Binarization with ',
```suggestion
    description='Binarization with selectional auto-encoders in Keras',
```
or something?

2020-10-16 08:54 UTC, kba commented on sbb_binarize/ocrd_cli.py
> +    color_coverted = cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
If I simply do `Image.fromarray(cv2_img)`, I get

```
  File "/home/kba/venv3/lib/python3.6/site-packages/PIL/Image.py", line 2753, in fromarray
    raise TypeError("Cannot handle this data type: %s, %s" % typekey) from e
TypeError: Cannot handle this data type: (1, 1), <i8
```

2020-10-16 08:55 UTC, kba commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
@vahidrezanezhad What are the consequences of using the "patches" approach?

2020-10-16 08:56 UTC, kba commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
It's all untested at this point because the conversion fails...

2020-10-16 08:57 UTC, kba commented on sbb_binarize/ocrd-tool.json
> +          "description": "models directory.",
The binarizer itself accepts relative paths, but we still have the `chdir(workspace.directory)` in the processor, so relative paths would have to be relative to the workspace :/

2020-10-16 09:02 UTC, kba commented on setup.py
> +    description='Binarization with ',
@vahidrezanezhad Is "Binarization with selectional auto-encoders in Keras" accurate in your opinion?

2020-10-16 09:05 UTC, kba commented on sbb_binarize/ocrd_cli.py
> +                regions = page.get_AllRegions(['Text', 'Table'])
You're right, probably 

```
page.get_TextRegion() + page.get_TableRegion()
```

would be enough

2020-10-16 09:05 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +    color_coverted = cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
Oh right, sorry. `SbbBinarizer.run` seems to just init its return arrays without dtype, so they get to be `np.int64`.

So if you want `L`, do `.astype(np.uint8)` before. If you want `1`, the above recipe should work regardless.

2020-10-16 09:07 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
I don't mean _functionally_, but from the modelling perspective. If training was on page images, I imagine textline crops (esp. if they are masked around some polygon already) won't work all that well.

2020-10-16 09:08 UTC, vahidrezanezhad commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
> @vahidrezanezhad What are the consequences of using the "patches" approach?

In the case of binarization, this parameter should be set "True", otherwise model will see image at once and the quality will be terrible.

2020-10-16 09:09 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "description": "models directory.",
Okay, so when your resource resolution arrives, this will automatically include the package data directory as search path?

2020-10-16 09:10 UTC, bertsky commented on sbb_binarize/ocrd_cli.py
> +                regions = page.get_AllRegions(['Text', 'Table'])
Yes. But then the line level does need the recursive `Text` iterator.

2020-10-16 09:10 UTC, kba commented on sbb_binarize/ocrd-tool.json
> +          "description": "models directory.",
yes

2020-10-16 09:21 UTC, vahidrezanezhad commented on setup.py
> +    description='Binarization with ',
> @vahidrezanezhad Is "Binarization with selectional auto-encoders in Keras" accurate in your opinion?

based on this paper "https://arxiv.org/abs/1706.10241", I would say yes this is what we have done in SBB for binarization. By the way "pixelwise binarization" can also be an option.

2020-10-16 09:28 UTC, kba commented on sbb_binarize/ocrd_cli.py
> +    color_coverted = cv2.cvtColor(img, cv2.COLOR_BGRA2RGB)
Thanks :bow: I chose the `L` variant. b7a6301

2020-10-16 09:29 UTC, kba commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
@vahidrezanezhad Does line-level binarization make sense with your approach?

2020-10-16 09:31 UTC, kba commented on setup.py
> +    description='Binarization with ',
e5bc557 "Pixelwise binarization with selectional auto-encoders in Keras" :)

2020-10-16 09:40 UTC, vahidrezanezhad commented on setup.py
> +    description='Binarization with ',
> [e5bc557](https://github.com/qurator-spk/sbb_binarization/commit/e5bc5572a22f47c0b797ea144237f7d72ae1fc85) "Pixelwise binarization with selectional auto-encoders in Keras" :)

Great mixing :)

2020-10-16 09:46 UTC, vahidrezanezhad commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
> @vahidrezanezhad Does line-level binarization make sense with your approach?

No, this SBB binarization has not exploited any line-level feature.

2020-10-16 09:50 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
Ok, then I'd recommend against exposing this parameter at all.

Also, how about setting it to `False` on region (or line) level, i.e. when running on region crops or textline crops?

2020-10-16 09:52 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
> > @vahidrezanezhad Does line-level binarization make sense with your approach?
> 
> No, this SBB binarization has not exploited any line-level feature.

What do you mean?

(The question was, does that approach work on textline crops, i.e. some other tool made a prior textline segmentation and now this tool is asked to binarize these segments, instead of the whole page.)

2020-10-16 09:54 UTC, kba commented on sbb_binarize/ocrd_cli.py
> +                regions = page.get_AllRegions(['Text', 'Table'])
a1c8f6f region level segmentation now only on top-level Text/Table regions, line-level fully recursive.

2020-10-16 10:00 UTC, vahidrezanezhad commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
> Ok, then I'd recommend against exposing this parameter at all.
> 
> Also, how about setting it to `False` on region (or line) level, i.e. when running on region crops or textline crops?

I would recommend to apply binarization on page region, since the best performance achieved when you feed model with real scale (better to say with patches set to "True") .  So, if you apply this on line level what is going to happen with False patches parameter? The textline region will be resized to input shape and I am sure that performance will be worse. 
On region level is the same. Patches parameter in all cases better to be True.

2020-10-16 10:09 UTC, vahidrezanezhad commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
> > > @vahidrezanezhad Does line-level binarization make sense with your approach?
> > 
> > 
> > No, this SBB binarization has not exploited any line-level feature.
> 
> What do you mean?
> 
> (The question was, does that approach work on textline crops, i.e. some other tool made a prior textline segmentation and now this tool is asked to binarize these segments, instead of the whole page.)

Models in this tools are trained with documents (lets say text regions ) and if you want to apply this on textline (if this is what you meant by line-level) crop, I highlight again the patches should be fixed to true and since I have not applied zero-padding for regions smaller than model input shape, for textlines this tool can have hard time . I can add zero-padding to resolve this problem in future :) Hope explanation was clear.

2020-10-16 10:11 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
@vahidrezanezhad understood – thanks for clarifying!

One follow-up though: Can you give an impression how sensitive these models are to different scales / pixel densities on the input side? (So, if the model has seen, say, only 600 DPI newspapers during training, will it still work on (patches of) 300 DPI books?)

2020-10-16 10:16 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
Thanks a lot – that was the explanation I was hoping for!

So I guess we should in fact disable the textline option on the parameter json side for now (but keep the implementation). If and when we do get models trained with zero padding, and the inference API also allows activating zero padding, then we can expose this to users again.

2020-10-16 10:20 UTC, vahidrezanezhad commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
> @vahidrezanezhad understood – thanks for clarifying!
> 
> One follow-up though: Can you give an impression how sensitive these models are to different scales / pixel densities on the input side? (So, if the model has seen, say, only 600 DPI newspapers during training, will it still work on (patches of) 300 DPI books?)

Actually, this tool has no problem with different pixel densities. But for the large scale texts like headers (Not any header I mean really large scale ones) or images I had problem to get my desired result. It was because of GT which does not include any images and any large scale texture. But this is also resolved with combination of 4 models. If by sbb binarization tool you apply all our 4 models you can see that it works mostly for big variety of scales. By the way make long story short, if you set patches to True and if you use all 4 models be sure that this tool will do sth :)

2020-10-16 10:23 UTC, vahidrezanezhad commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
> Thanks a lot – that was the explanation I was hoping for!
> 
> So I guess we should in fact disable the textline option on the parameter json side for now (but keep the implementation). If and when we do get models trained with zero padding, and the inference API also allows activating zero padding, then we can expose this to users again.

Yes for now I think it is better to be disabled for textlines. I am right now busy with our new tool but I will resolve issues for textlines binarization as soon as possible.

2020-10-16 10:33 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
> Actually, this tool has no problem with different pixel densities.

Okay, even if they differ widely, like using the model on 100 or 1200 DPI scans?

> But for the large scale texts like headers (Not any header I mean really large scale ones) or images I had problem to get my desired result. It was because of GT which does not include any images and any large scale texture. But this is also resolved with combination of 4 models.

Oh, now I get it, that's why the [run method](https://github.com/OCR-D/sbb_binarization/blob/a1c8f6f4650591eda9cda8af5cb17237b6b2deb0/sbb_binarize/sbb_binarize.py#L207) predicts on multiple models and then assigns foreground wherever any of them predicted fg. So these models actually were trained on multiple scales.

This is reminiscent of [multi-scale Sauvola](https://www.lrde.epita.fr/dload/papers/lazzara.13.ijdar.pdf) running on different image resolutions, and then re-combining them morphologically. Do you think there would be merit in having such morphological restrictions (and a well-defined order from largest to smallest) here as well?

Also, how does this interface (practically) with text/non-text segmentation? If images are somewhat problematic, should they be detected on the raw image and then removed from the binarized image before entering sbb_textline_detector?

2020-10-16 10:38 UTC, kba commented on sbb_binarize/ocrd-tool.json
> +          "enum": ["page", "region", "line"],
645ec41 disabled line-level binarization in the ocrd-tool.json for now.

2020-10-16 10:45 UTC, vahidrezanezhad commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
> > Actually, this tool has no problem with different pixel densities.
> 
> Okay, even if they differ widely, like using the model(s) on 100 or 1200 DPI scans?
> 
> > But for the large scale texts like headers (Not any header I mean really large scale ones) or images I had problem to get my desired result. It was because of GT which does not include any images and any large scale texture. But this is also resolved with combination of 4 models.
> 
> Oh, now I get it, that's why the [run method](https://github.com/OCR-D/sbb_binarization/blob/a1c8f6f4650591eda9cda8af5cb17237b6b2deb0/sbb_binarize/sbb_binarize.py#L207) predicts on multiple models and then assigns foreground wherever any of them predicted fg. So these models actually were trained on multiple scales.
> 
> This is reminiscent of [multi-scale Sauvola](https://www.lrde.epita.fr/dload/papers/lazzara.13.ijdar.pdf) running on different image resolutions, and then re-combining them morphologically. Do you think there would be merit in having such morphological restrictions (and a well-defined order from largest to smallest) here as well?
> 
> Also, how does this interface (practically) with text/non-text segmentation? If images are somewhat problematic, should they be detected on the raw image and then removed from the binarized image before entering sbb_textline_detector?


I am not 100% sure but I think it should work for any dpis. If not do not worry we have also developed sth for it :)


Yes, you are right those 4 models are trained with different scales. 

In sbb we have already recognized that how important is scale and somehow the dpi of documents (we get to this point based on ocr-scans documents which were used with ocr society, they were low dpi and low scale images and our sbb-textline-detector had hard time with layout detection). So we decided to train 2 models. First a model to enhance image (for enhancing we also needed a right scale) and second a model to detect scale of document or better to say number of columns in document. I am happy to say both are trained and results are really good. We have integrated this 2 models in our new layout detector and you will see it soon. Again, if our binarization is not working becuase of scale or quality of document, now we can first prepare document with those model and then feed it to binarization model.

2020-10-16 10:54 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
> So we decided to train 2 models. First a model to enhance image (for enhancing we also needed a right scale) and second a model to detect scale of document or better to say number of columns in document. I am happy to say both are trained and results are really good. We have integrated this 2 models in our new layout detector and you will see it soon. Again, if our binarization is not working becuase of scale or quality of document, now we can first prepare document with those model and then feed it to binarization model.

Awesome! Looking forward to seeing the new version of the segmentation, and feeling much better about this knowing that your 4-scaled binarization models will also benefit.

2020-10-16 10:55 UTC, bertsky commented on sbb_binarize/ocrd-tool.json
> +          "description": "by setting this parameter to true you let the model to see the image in patches.",
@kba we should probably document all this in our workflow guide or wiki etc.

2020-10-22 10:53 UTC, vahidrezanezhad approved these changes

2020-10-22 10:53 UTC, vahidrezanezhad approved these changes

2020-10-22 10:54 UTC, vahidrezanezhad approved these changes

2020-10-22 10:56 UTC, vahidrezanezhad approved these changes

2020-10-22 10:58 UTC, vahidrezanezhad approved these changes

2020-10-22 10:59 UTC, vahidrezanezhad approved these changes

2020-10-22 10:59 UTC, vahidrezanezhad approved these changes

2020-10-22 11:00 UTC, merged