add Docker and GHA CD via Dockerhub
qurator-spk/sbb_binarization pull request #70
Opened 2024-09-30 19:27 UTC by bertsky

2024-10-10 14:55 UTC, kba approved these changes
LGTM.

I am aware that it has been deprecated for a while but until we have the binarization functionality in eynollah available via OCR-D interface, this is still one of the best binarizers out there and we should support it as a slim container in ocrd_all.

2024-10-11 12:20 UTC, bertsky commented
Py3.9 and 3.10 failures are extremely strange:

```python
>>> import sbb_binarize.cli
>>> type(sbb_binarize.cli)
>>> sbb_binarize.cli is None
>>> import inspect
>>> inspect.ismodule(sbb_binarize.cli)
>>>
```
So it seems that Python has some kind of `null` type not made explicit. No idea what's wrong with the packaging. The `RECORD` seems fine, it lists all module files.

2024-10-14 11:32 UTC, bertsky commented
> Py3.9 and 3.10 failures are extremely strange:
> 
> ```python
> >>> import sbb_binarize.cli
> >>> type(sbb_binarize.cli)
> >>> sbb_binarize.cli is None
> >>> import inspect
> >>> inspect.ismodule(sbb_binarize.cli)
> >>>
> ```
> 
> So it seems that Python has some kind of `null` type not made explicit. No idea what's wrong with the packaging. The `RECORD` seems fine, it lists all module files.

Migrating from setup.py to pyproject.toml did not help.

2024-10-14 11:33 UTC, bertsky commented
I'll also relax TF requirement slightly (to be in line with eynollah) – tested: no different between 2.11 and 2.12.

2024-10-14 15:30 UTC, bertsky commented
oh, wow – relaxing the TF requirements also magically fixed the problem with Py3.9 and 3.10! (I wonder why we did not receive a build-time error saying that no such TF version is available, though...)

2024-10-15 07:02 UTC, joschrew commented
I just looked at the changed files without testing anything yet. The Dockerfile still uses setup.py, which is deleted and does not copy pyproject.toml.
Also I am wondering if the image should me based on the special ocr-d-tensorflow image as tensorflow is a requirement. But I might be totally wrong regarding the latter.

2024-10-15 07:56 UTC, joschrew requested changes
The dockerimage does not work for me without these changes. I testet `ocrd-sbb-binarize --help` and a simple binarization, which took quite long (72 secs for a single image). 
Maybe it would also be good to include one ore more models into the dockerimage, because I had to download one by myself with resmgr, but I am not sure if this should be included.

2024-10-15 07:56 UTC, joschrew commented on Dockerfile
> +COPY setup.py .
```suggestion
COPY pyproject.toml .
```
copy-paste error

2024-10-15 07:56 UTC, joschrew commented on Dockerfile
> +COPY ocrd-tool.json .
```suggestion
COPY sbb_binarize/ocrd-tool.json .
```
Not sure if that is really needed though, but we do this in every other Dockerfile as well

2024-10-15 07:56 UTC, joschrew commented on pyproject.toml
> +sbb_binarize = ["sbb_binarize/*.json"]
```suggestion
[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"*" = ["*.json"]
```
Including the ocrd-tool.json worked for me in a local venv but not in Docker. This change makes it work but I am not sure if this is the best way of doing it

2024-10-15 10:44 UTC, bertsky commented on Dockerfile
> +COPY ocrd-tool.json .
Not needed. The root ocrd-tool.json is a symlink that resolves correctly in the build context, so it has the same effect. (But generally, writing Dockerfiles for OCR-D modules, you have to be much more careful with your form, because the target of the symlink might be some other location deeper inside the package.)

2024-10-15 10:51 UTC, bertsky commented
> which took quite long (72 secs for a single image).

yes, without a GPU this is slow, and even with it is not efficient. But that's well known and not the issue here.



> Maybe it would also be good to include one ore more models into the dockerimage, because I had to download one by myself with resmgr, but I am not sure if this should be included.

No, that would just bloat the image. Downloading models in advance of using is the normal procedure for OCR-D. We don't want to reign in the admin's decision where to store persistent data (like models, which should not change as often as code).

> Also I am wondering if the image should me based on the special ocr-d-tensorflow image as tensorflow is a requirement. But I might be totally wrong regarding the latter.

In principle, yes. But since here, TF is pinned to `<=2.12`, while our current `core-cuda-tf2` is unrestricted on Py38 (and thus pulls 2.13) … https://github.com/OCR-D/core/blob/85bde1574293ea8b7ba29255fbb8e07312c28eb1/Makefile#L153-L158 … it would not help (only increase the image size even more).

But we should at least switch to `core-cuda` then...

2024-10-15 17:51 UTC, bertsky commented
So this is ready IMO. Fixes #67 and also brings support for Python 3.9 and 3.10.

2024-10-16 11:07 UTC, kba approved these changes

2024-10-16 11:11 UTC, joschrew approved these changes

2024-10-16 11:21 UTC, cneud commented
Dear all, thx - I can merge this today but would have 2 more small requests:
- can we also include Python 3.11 in the CI please
- Tensorflow can be relaxed to 2.12.x iiuc

2024-10-16 11:42 UTC, bertsky commented
@cneud done!

> * can we also include Python 3.11 in the CI please

let's see if it works

> * Tensorflow can be relaxed to 2.12.x iiuc

IMO it would make sense now to relax Eynollah's current pin (2.12.1) as well (2.12.x) – so we don't reintroduce the conflict if some TF 2.12.2 should be published

2024-10-16 12:03 UTC, cneud commented
> relax Eynollah's current pin (2.12.1) as well (2.12.x)

Will do and thanks again! Ready to merge in 3, 2, 1...

2024-10-16 12:03 UTC, cneud approved these changes

2024-10-16 12:04 UTC, merged